# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 风吹过
description: > # this means to ignore newlines until "baseurl:"
  Material theme based on <a href="http://materializecss.com">Materialize.css</a> for jekyll sites
baseurl: "/sotex.github.io"
url: "https://sotex.github.io"
permalink: /:year/:month/:day/:title
repository: sotex/sotex.github.io
paginate: 5

# MatJek specific configurations
github_profile: "https://github.com/sotex"
user: "乌合之众"
user_email: "ymwh@foxmail.com"
contact_url: "https://fanyi.baidu.com/#zh/en/%E9%82%AE%E7%AE%B1%EF%BC%9Aymwh%40foxmail.com%20%E6%88%96%20liu2g%40outlook.com%0A%E5%8D%9A%E5%AE%A2%EF%BC%9Ahttps%3A%2F%2Fwww.cnblogs.com%2Foloroso%2F%0A%E7%94%B5%E8%AF%9D%EF%BC%9A%E9%99%90%E4%BA%8E%E5%BD%93%E5%89%8D%E7%A4%BE%E4%BC%9A%E7%8E%B0%E7%8A%B6%EF%BC%8C%E4%B8%8D%E4%BE%BF%E5%85%AC%E5%BC%80%0A%E7%8E%B0%E5%9C%A8%E5%9C%B0%EF%BC%9A%E5%8C%97%E4%BA%AC%0A%E6%9D%A5%E6%BA%90%E5%9C%B0%EF%BC%9A%E6%B9%96%E5%8D%97"
#google_tracking_id: "UA-96359860-1"
#google_site_verification: "UA-96359860-1"
#disqus_shortname: "matjek"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true